
server:
  #端口
  port: 8081

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "001020"
    druid:
      #最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 10
      # 连接超时事件
      max-wait: 60000
      #自动提交
      default-auto-commit: true
      #连接检测
      validationQuery: SELECT 1 FROM DUAL
      # 空间检查
      timeBetweenEvictionRunsMillis: 60000
      # 空闲检查
      minEvictableIdleTimeMillis: 300000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #redis连接配置
  redis:
    timeout: 10000ms
    host: localhost
    password: "001020"
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 10
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲时间
        max-idle: 100
        #最小空闲时间
        min-idle: 5

#mybatis plus 配置
mybatis-plus:
  #自动别名
  type-aliases-package: com.chen.server.pojo
  configuration:
    #日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭自动驼峰命名
    map-underscore-to-camel-case: false

#sql打印
logging:
  level:
    com.chen.server.mapper: debug

jwt:
  #JWT 存储的请求头
  tokenHeader: Authorization
  #JWT 加密密钥
  secret: yeb-secret
  #JWT 超时过期事件
  expiration: 604800
  #JWT 负载中拿到开头
  tokenHead: Bearer


